name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-5_0_22:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build EPASWMM 5.0.22 Docker image
      run: docker build --build-arg EPASWMM_VERSION=5.0.22 . --tag epanet:5.0.22-$(date +%s)
  build-5_1_0:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build EPASWMM 5.1.0 Docker image
      run: docker build --build-arg EPASWMM_VERSION=5.1.0 . --tag epanet:5.1.0-$(date +%s)
  build-5_1_1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build EPASWMM 5.1.1 Docker image
      run: docker build --build-arg EPASWMM_VERSION=5.1.1 . --tag epanet:5.1.1-$(date +%s)
  build-5_1_2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build EPASWMM 5.1.2 Docker image
      run: docker build --build-arg EPASWMM_VERSION=5.1.2 . --tag epanet:5.1.2-$(date +%s)
  build-5_1_3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build EPASWMM 5.1.3 Docker image
      run: docker build --build-arg EPASWMM_VERSION=5.1.3 . --tag epanet:5.1.3-$(date +%s)
  build-5_1_4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build EPASWMM 5.1.4 Docker image
      run: docker build --build-arg EPASWMM_VERSION=5.1.4 . --tag epanet:5.1.4-$(date +%s)
  build-5_1_5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build EPASWMM 5.1.5 Docker image
      run: docker build --build-arg EPASWMM_VERSION=5.1.5 . --tag epanet:5.1.5-$(date +%s)
  build-5_1_6:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build EPASWMM 5.1.6 Docker image
      run: docker build --build-arg EPASWMM_VERSION=5.1.6 . --tag epanet:5.1.6-$(date +%s)
  build-5_1_7:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build EPASWMM 5.1.7 Docker image
      run: docker build --build-arg EPASWMM_VERSION=5.1.7 . --tag epanet:5.1.7-$(date +%s)
  build-5_1_8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build EPASWMM 5.1.8 Docker image
      run: docker build --build-arg EPASWMM_VERSION=5.1.8 . --tag epanet:5.1.8-$(date +%s)
  build-5_1_9:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build EPASWMM 5.1.9 Docker image
      run: docker build --build-arg EPASWMM_VERSION=5.1.9 . --tag epanet:5.1.9-$(date +%s)
  build-5_1_10:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build EPASWMM 5.1.10 Docker image
      run: docker build --build-arg EPASWMM_VERSION=5.1.10 . --tag epanet:5.1.10-$(date +%s)
  build-5_1_11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build EPASWMM 5.1.11 Docker image
      run: docker build --build-arg EPASWMM_VERSION=5.1.11 . --tag epanet:5.1.11-$(date +%s)
  build-5_1_12:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build EPASWMM 5.1.12 Docker image
      run: docker build --build-arg EPASWMM_VERSION=5.1.12 . --tag epanet:5.1.12-$(date +%s)
  build-5_1_13:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build EPASWMM 5.1.13 Docker image
      run: docker build --build-arg EPASWMM_VERSION=5.1.13 . --tag epanet:5.1.13-$(date +%s)
  build-5_1_14:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build EPASWMM 5.1.14 Docker image
      run: docker build --build-arg EPASWMM_VERSION=5.1.14 . --tag epanet:5.1.14-$(date +%s)
  build-5_1_15:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build EPASWMM 5.1.15 Docker image
      run: docker build --build-arg EPASWMM_VERSION=5.1.15 . --tag epanet:5.1.15-$(date +%s)
